services:
    chain_command.command_chain:
        class: ChainCommandBundle\Chain\CommandChain

    chain.command_listener:
        class: ChainCommandBundle\EventListener\ChainCommandListener
        arguments:
            - "@chain_command.command_chain"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: console.command }